/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Patient;

import model.EcoSystem;
import model.Employee.Employee;
import model.Enterprise.Enterprise;
import model.WorkQueue.Order;
import model.WorkQueue.Product;
import model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import util.TwilioSMSUtil;
import static util.UtilClass.isOnlyTextWithWhiteSpaces;
import static util.UtilClass.isPhoneNumberVerified;
import static util.UtilClass.isValidTextString;

/**
 *
 * @author udaykk
 */
public class Payment extends javax.swing.JPanel {

    Enterprise enterprise;
    WorkRequest workRequest;
    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    Order order;

    /**
     * Creates new form Payment
     */
    public Payment(JPanel userProcessContainer, WorkRequest workRequest, Enterprise enterprise, EcoSystem ecoSystem, Order order) {
        initComponents();
        this.enterprise = enterprise;
        this.workRequest = workRequest;
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.order = order;
        lblTotal.setText(String.valueOf(order.totalHospital()));
        System.out.println("inside payment");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCard = new javax.swing.JTextField();
        btnCompletePayment = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtMobile = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1);
        jLabel1.setBounds(530, 280, 162, 17);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Mobile No");
        add(jLabel2);
        jLabel2.setBounds(530, 370, 162, 17);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(710, 273, 190, 30);
        add(txtCard);
        txtCard.setBounds(710, 313, 190, 30);

        btnCompletePayment.setBackground(new java.awt.Color(0, 153, 0));
        btnCompletePayment.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        btnCompletePayment.setForeground(new java.awt.Color(255, 255, 255));
        btnCompletePayment.setText("Complete payment");
        btnCompletePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletePaymentActionPerformed(evt);
            }
        });
        add(btnCompletePayment);
        btnCompletePayment.setBounds(650, 500, 180, 60);

        btnBack.setBackground(new java.awt.Color(0, 102, 204));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(17, 9, 90, 40);

        lblTotal.setText("<Order Total>");
        add(lblTotal);
        lblTotal.setBounds(710, 230, 162, 30);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Order Total:");
        add(jLabel3);
        jLabel3.setBounds(530, 240, 162, 17);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("CardNumber");
        add(jLabel5);
        jLabel5.setBounds(530, 320, 162, 17);
        add(jtxtMobile);
        jtxtMobile.setBounds(710, 360, 190, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCompletePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletePaymentActionPerformed
        // TODO add your handling code here:

        try {
            if (!isOnlyTextWithWhiteSpaces(txtName.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter valid name");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter valid name");
        }
        
        

        try {
            if (!isValidTextString(txtCard.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter valid card no");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter valid card no");
        }


        try {
            if (!isPhoneNumberVerified(jtxtMobile.getText())) {
                JOptionPane.showMessageDialog(this, "Please enter valid phone");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter valid phone");
        }

        if (order.getProductList().size() == 0) {
            JOptionPane.showMessageDialog(this, "Please add items to the cart");
            return;
        }
        if (txtCard.getText().isEmpty() || txtName.getText().isEmpty() || jtxtMobile.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory");
            return;
        }
        if (checkCardValid(txtCard.getText())) {
            Employee customer = new Employee(txtName.getText(), txtCard.getText());
            Order newOrder = new Order();
            newOrder.setSender(order.getSender());
            newOrder.setNetworkName(order.getNetworkName());
            newOrder.setSenderEnterprise(order.getSenderEnterprise());
            newOrder.setReceiverEnterprise(order.getReceiverEnterprise());
            newOrder.setStatus("waiting for Hospital to accept");
            for (Product prod : order.getProductList()) {
                newOrder.getProductList().add(prod);
            }
            ecoSystem.getWorkQueue().getWorkRequestList().add(newOrder);
            order.getProductList().clear();
            String mobile = "+1" + jtxtMobile.getText();
            TwilioSMSUtil
                    .sendTextMessage(mobile,
                            "Hi " + txtName.getText() + ", " + "Thank you for choosing us. Your payment has been debited from Card ending xxxx" + txtCard.getText().substring(12) + ". Stay safe and Healthy.");
            workRequest.setStatus("waiting for Hospital admin to accept");
            JOptionPane.showMessageDialog(this, "Thankyou for shopping with us");

        } else {
            JOptionPane.showMessageDialog(this, "Please enter valid card number");
        }

    }//GEN-LAST:event_btnCompletePaymentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProductList dwjp = (ProductList) component;
        dwjp.populateProductList();
        dwjp.populateOrder();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCompletePayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtxtMobile;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCard;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    public boolean checkCardValid(String card) {
        Pattern pattern = Pattern.compile("^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\\d{11})$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(card);
        return matcher.find();
    }

}
