/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.neuuday.assignment1.model.ContactInfo;
import com.neuuday.assignment1.model.Employee;
import com.neuuday.assignment1.model.EmployeeDirectory;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import util.UtilClass;
import java.util.Date;

/**
 *
 * @author udaykk
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    EmployeeDirectory directory;
    String fileName = null;
    byte[] employee_image = null;

    public CreateJPanel(EmployeeDirectory directory) {
        initComponents();
        this.directory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEmployeeId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        txtFldEmployeeId = new javax.swing.JTextField();
        txtFldName = new javax.swing.JTextField();
        txtFldAge = new javax.swing.JTextField();
        savejButton = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtFldLevel = new javax.swing.JTextField();
        lblTeamInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtFldTeamInfo = new javax.swing.JTextField();
        txtFldPositionTitle = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtFldPhoneNumber = new javax.swing.JTextField();
        txtFldEmail = new javax.swing.JTextField();
        txtFldStartDate = new javax.swing.JTextField();
        comboBoxGender = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnUploadPhoto = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();
        btnCancelCreation = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1250, 850));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblTitle.setText("Create Employee");

        lblEmployeeId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblEmployeeId.setText("Employee Id");

        lblName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblName.setText("Name");

        lblStartDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblStartDate.setText("Start Date");

        lblLevel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblLevel.setText("Level");

        txtFldEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldEmployeeIdActionPerformed(evt);
            }
        });

        txtFldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldNameActionPerformed(evt);
            }
        });

        txtFldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldAgeActionPerformed(evt);
            }
        });

        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblAge.setText("Age");

        lblGender.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblGender.setText("Gender");

        txtFldLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldLevelActionPerformed(evt);
            }
        });

        lblTeamInfo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblTeamInfo.setText("Team Info");

        lblPositionTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPositionTitle.setText("Position Title");

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        txtFldTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldTeamInfoActionPerformed(evt);
            }
        });

        txtFldPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldPositionTitleActionPerformed(evt);
            }
        });

        lblPhoneNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        txtFldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldEmailActionPerformed(evt);
            }
        });

        txtFldStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldStartDateActionPerformed(evt);
            }
        });

        comboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Others" }));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Photo");

        btnUploadPhoto.setText("Browse");
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });

        btnCancelCreation.setText("Cancel");
        btnCancelCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelCreationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(282, 282, 282))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(btnUploadPhoto))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(savejButton)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelCreation)))
                        .addGap(18, 18, 18)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(346, 346, 346))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPositionTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTeamInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmployeeId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFldPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFldPositionTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFldTeamInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFldLevel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFldStartDate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboBoxGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFldAge, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFldName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFldEmployeeId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(347, 347, 347))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTeamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(lblPositionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFldEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFldName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFldAge)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxGender)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldStartDate)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldLevel)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldTeamInfo)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldPositionTitle)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldPhoneNumber)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldEmail)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnUploadPhoto)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savejButton)
                            .addComponent(btnCancelCreation))
                        .addGap(289, 289, 289))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblEmployeeId, lblName, txtFldEmployeeId});

    }// </editor-fold>//GEN-END:initComponents

    private void txtFldEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldEmployeeIdActionPerformed

    private void txtFldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldNameActionPerformed

    //This button collects all the required text fields data and add it to the list
    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
        if (!UtilClass.isOnlyTextWithWhiteSpaces(txtFldName.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Please enter valid name.");
            return;
        }
        try {
            if (!UtilClass.isOnlyNumber(txtFldAge.getText()) || Integer.parseInt(txtFldAge.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter valid age.");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter valid age.");
            return;
        }

        if (!UtilClass.isOnlyText("" + comboBoxGender.getSelectedItem())) {
            JOptionPane.showMessageDialog(this, "Please enter valid gender.");
            return;
        }
        Date date = UtilClass.convertStringToDate(txtFldStartDate.getText());
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Please enter valid date input.");
            return;
        }

        if (!UtilClass.isPhoneNumberVerified(txtFldPhoneNumber.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter valid 10 digit phone number.");
            return;
        }

        if (!UtilClass.isEmailValidated(txtFldEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter valid email id");
            return;
        }

        String employeeId = txtFldEmployeeId.getText();
        String name = txtFldName.getText().trim();
        int age = Integer.parseInt(txtFldAge.getText());
        String gender = "" + comboBoxGender.getSelectedItem();
        Date startDate = date;
        String level = txtFldLevel.getText();
        String teamInfo = txtFldTeamInfo.getText();
        String positionTitle = txtFldPositionTitle.getText();
        String phoneNumber = txtFldPhoneNumber.getText();
        byte[] photo = employee_image;

        String emailAddress = txtFldEmail.getText();
        Employee emp = directory.addEmployeeToDirectory();
        emp.setEmployeeId(employeeId);
        emp.setName(name);
        emp.setAge(age);
        emp.setGender(gender);
        emp.setStartDate(startDate);
        emp.setLevel(level);
        emp.setTeamInfo(teamInfo);
        emp.setPositionTitle(positionTitle);
        ContactInfo contactInfo = new ContactInfo(phoneNumber, emailAddress);
        emp.setContactInfo(contactInfo);
        emp.setPhoto(photo);
        JOptionPane.showMessageDialog(this, "Data added successfully.");

        clearViewFields();

//        employeeIdjTextField.setText("");
//        namejTextField.setText("");
//        genderjTextField.setText("");
//        leveljTextField.setText("");

    }//GEN-LAST:event_savejButtonActionPerformed

    private void txtFldTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldTeamInfoActionPerformed

    private void txtFldPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldPositionTitleActionPerformed

    //Upload button is used to upload the picture and convert it into byte type
    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("png", "jpg", "jpeg");
        fileChooser.addChoosableFileFilter(fileNameExtensionFilter);
        int showOpenBox = fileChooser.showOpenDialog(null);
        if (showOpenBox == JFileChooser.APPROVE_OPTION) {
            File selectedImage = fileChooser.getSelectedFile();
            String imagePath = selectedImage.getAbsolutePath();
            fileName = imagePath;
            JOptionPane.showMessageDialog(this, imagePath);
            ImageIcon ii = new ImageIcon(new ImageIcon(imagePath).getImage().getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), WIDTH));
            lblPhoto.setIcon(ii);
        }

        try {
            File image = new File(fileName);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream arrayOutputStream = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int num; (num = fis.read(buf)) != -1;) {
                arrayOutputStream.write(buf, 0, num);
            }
            employee_image = arrayOutputStream.toByteArray();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnUploadPhotoActionPerformed

    private void txtFldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldEmailActionPerformed

    private void txtFldStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldStartDateActionPerformed

    private void txtFldLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldLevelActionPerformed

    private void btnCancelCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelCreationActionPerformed
        // TODO add your handling code here:
        clearViewFields();
    }//GEN-LAST:event_btnCancelCreationActionPerformed

    private void txtFldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldAgeActionPerformed

    //it clears all the existing text fields and it helps in resetting the data
    public void clearViewFields() {
        txtFldEmployeeId.setText("");
        txtFldName.setText("");
        txtFldAge.setText("");
        comboBoxGender.setSelectedIndex(0);
        txtFldStartDate.setText("");
        txtFldLevel.setText("");
        txtFldTeamInfo.setText("");
        txtFldPositionTitle.setText("");
        txtFldPhoneNumber.setText("");
        txtFldEmail.setText("");
        lblPhoto.setIcon(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelCreation;
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.JComboBox<String> comboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeId;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton savejButton;
    private javax.swing.JTextField txtFldAge;
    private javax.swing.JTextField txtFldEmail;
    private javax.swing.JTextField txtFldEmployeeId;
    private javax.swing.JTextField txtFldLevel;
    private javax.swing.JTextField txtFldName;
    private javax.swing.JTextField txtFldPhoneNumber;
    private javax.swing.JTextField txtFldPositionTitle;
    private javax.swing.JTextField txtFldStartDate;
    private javax.swing.JTextField txtFldTeamInfo;
    // End of variables declaration//GEN-END:variables
}
